### ISSUE TITLE
Reimplement "clone" expression

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#293]
This currently relies on the old serialization code. That's (1) inefficient, and (2) that code will go away. We need to reimplement the logic. (@rsmmr has a starting point for that work, ask him about it).

**Comment by rsmmr** [comment]
Started in https://github.com/zeek/zeek/tree/topic/robin/clone

**Comment by 0xxon** [comment]
Done in topic/johanna/clone, see PR https://github.com/zeek/zeek/pull/376

**Comment by jsiwek** [comment]
#376 is merged now, should we call this closed now even with `EntropyVal` still using the old serialization for cloning ?  It didn't seem like it would be particularly hard to convert that one too:  just add a way to copy the `RandTest` member.  Or am I missing something ?

**Comment by rsmmr** [comment]
@0xxon Is the code already protecting about reference cycles? That was a piece still missing in my first version.

**Comment by jsiwek** [comment]
What's "protect" mean more specifically wrt to reference cycles and what should be supported ?

Is there a point doing any handling of cycles in clone/copy if it's going to be a landmine more generally due to lack of smarter visitation process (e.g. a simple thing such as trying to print a value with reference cycles is going to blow up) ?

If cycles are supposed to be detected and rejected more generally by the language, then I'd guess the clone/copy code doesn't even need to do anything specifically, rather it's the assignment/mutator methods of MutableVal subclasses that need to detect if a cycle is being made and reject it via runtime exception.

**Comment by 0xxon** [comment]
It depends what you mean about protecting reference cycle. There is a bit of code in there (which I actually think you wrote) that tracks if the same Val is cloned several times in one go. If during one clone operation the same pointer is cloned several times, the copy is returned. 

There is a test for this - it does not exactly check reference cycles; however it checks that a record that references the same val (in that case subrecord) several times will only have one instance of the subrecord that is refered to several times. This should be good enough for cycles too - since an already cloned object will immediately be returned and not be recursively cloned again.

Or were you thinking about something else?

**Comment by 0xxon** [comment]
And second answer - since the entropyval clone implementation was going to look very similar to the serialize/deserialize implementation (copy everything manually), and since we still need one for broker, I was just going to be lazy and use those. That being said we can write one :)

**Comment by rsmmr** [comment]
What I meant is things like this: 

```
type X: record  {
        x: any &optional;
        };

event zeek_init()
        {
        local x: X;
        x$x = x;
        print copy(x);
        }
```

That's stack overflowing currently (just tried it :)

I think we should move towards not allowing this, but technically right now we do: there's nothing preventing users from setting up structures like that, nor do we say anywhere that they shouldn't. Given that, I think we need to handle it gracefully. I would go so far and say that that indeed applies everywhere: any traversal should catch such cycles. We could decide to abort in those cases, but it would be a change of semantics that I think needs some thought & discussion. As long as we don't do that, I'd say deep copying should reconstruct the cycle (which will cause a bit of additional overhead unfortunately).

**Comment by jsiwek** [comment]
The previous version of copy/clone (i.e. the serialization logic) also stack overflows in the face of a reference cycle, so it at least wouldn't be a regression.

If the desired behavior is for us to catch the creation of a reference cycle and prevent it at that point in time (e.g. throw an interpreter exception), I don't see that requiring any logic specific to copy/clone.

So there's maybe a case for punting on doing anything now inside of the copy/clone logic if we'd likely just remove it upon the arrival of a generalized cycle-detection-and-prevention feature.

**Comment by rsmmr** [comment]
Oh, the old code does? That was a bug then, the serialization code was supposed to handle & restore cycles.

I don't think we can generally detect cycles at creation time; only at times when we traverse. I'll give this detection a quick try, I think it's not hard to add and we can see if it impacts performance substantially.

**Comment by rsmmr** [comment]
I believe we can close this now, will catch the missing EntropyVal change later.
